#!/bin/bash

sleep 20

rsstail -n1 -1 -N -u http://www.datatau.com/rss

MAIN_DOMAIN='http://www.datatau.com/'

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  xdg-open "${MAIN_DOMAIN}"
fi

## rsstail -t -u 'http://news.startup.ml/rss' | sed -e 's/\n/\n/g' | cut -d \   -f 1



# output=($(python3 datatau.py))

# echo "$output" | sed -r 's/\*/\ /g'

# exit
